
city_country_flags = {
    "Athens": ":Greece: ",
    "Austin": ":United_States: ",
    "Berlin": ":Germany: ",
    "Boston": ":United_States: ",
    "Buenos Aires": ":Argentina: ",
    "Chicago": ":United_States: ",
    "Dallas": ":United_States: ",
    "Kansas City": ":United_States: ",
    "Lisbon": ":Portugal: ",
    "London": ":England: ",
    "Madrid": ":Spain: ",
    "New York": ":United_States: ",
    "Mexico City": ":Mexico: ",
    "Nice": ":France: ",
    "Paris": ":France: ",
    "Rio de Janeiro": ":Brazil: ",
    "Rome": ":Italy: ",
    "San Antonio": ":United_States: ",
    "San Francisco": ":United_States: ",
    "Sao Paulo": ":Brazil: ",
    "Venice": ":Italy: ",
    "Vienna": ":Austria: "
}


cities_list = [
    "- Random Selection -",
    "Athens",
    "Austin",
    "Berlin",
    "Boston",
    "Buenos Aires",
    "Chicago",
    "Dallas",
    "Kansas City",
    "Lisbon",
    "London",
    "Madrid",
    "New York",
    "Mexico City",
    "Nice",
    "Paris",
    "Rio de Janeiro",
    "Rome",
    "San Antonio",
    "San Francisco",
    "Sao Paulo",
    "Venice",
    "Vienna"
    ]